repos:
  # ---------------------------------------------------------------------------
  # Lint: Ruff + Black + mypy
  # ---------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

  # ---------------------------------------------------------------------------
  # Run tests: fast feedback on commits
  # ---------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]

  # ---------------------------------------------------------------------------
  # Run documentation tests: fast feedback on commits
  # ---------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: test-docs
        name: test-docs
        entry: make test-docs
        language: system
        pass_filenames: false
        stages: [pre-commit]

  #---
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.0  # Replace with latest tag
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
